version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: job-finder-companion
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "9906:3306"
  web:
    image: nidup/job-finder-companion-web:latest
    container_name: web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
